### ISSUE TITLE
Change primary color and update style

### ISSUE THREAD

**Issue by bonustrack** [busyorg/busy#1549]
- [ ] Change primary color to: `#1eacf8`
- [ ] Create secondary color : `#0274dc`
- [ ] Use secondary color on buttons follow instead of the primary color
- [ ] Change topic style to: `color: #777676; background-color: #e9e7e7;` and remove borders
